remaster:
  h1n1:
    R0: 1.3
    delta: 91.3125
    p: 0.015
    sim-time: 0.25
    change-time-R: 
    change-time-P: 

  tb:
    R0: 2.0&#x20;1.1
    delta: 0.125
    p: 0.08
    sim-time: 25.0
    change-time-R: 12.5
    change-time-P: ""

  sars-cov-2:
    R0: 2.5
    delta: 36.525
    p: 0.8
    sim-time: 0.16
    change-time-R: 0
    change-time-P: 0

  saureus:
    R0: 2.0&#x20;1.0
    delta: 0.93
    p: 0.0&#x20;0.01
    sim-time: 25.0
    change-time-R: 10
    change-time-P: 22